package Tugas8;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

public class PenentuJumlahHari extends javax.swing.JFrame {
    private HitungHari hitungHari;  //Membuat objek dari class HitungHari untuk menghitung jumlah Hari
    /**
     * Creates new form PenentuJumlahHari
     */
    //Konstruktor untuk inialisasi komponen dan event listener
    public PenentuJumlahHari() {
        initComponents();   //Memanggil komponen untuk inialisasi komponen GUI
        hitungHari = new HitungHari();  //Inisialisasi objek hitungHari
        
        //Mengatur opsi bulan pada JComboBox
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{
            "Januari", "Februari", "Maret", "April", "Mei", "Juni", 
            "Juli", "Agustus", "September", "Oktober", "November", "Desember"
        }));

        //Action listener untuk tombol Hitung
        hitungJumlahHari.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                hitungJumlahHariActionPerformed(evt);   //Memanggil  method untuk hitung jumlah hari
            }
        });

        //Action listener untuk tombol Hapus
        hapusInput.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                hapusInputActionPerformed(evt);
            }
        });

        //Action listener untuk tombol Simpan
        simpanHasil.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                simpanHasilActionPerformed(evt);
            }
        });

        //Action listener untuk tombol Keluar
        keluarAplikasi.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                keluarAplikasiActionPerformed(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")  //Mengabaikan peringatan kompilasi yang tidak diperlukan
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        hitungJumlahHari = new javax.swing.JButton();
        hapusInput = new javax.swing.JButton();
        simpanHasil = new javax.swing.JButton();
        keluarAplikasi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Aplikasi Penentu Jumlah Hari");

        jPanel1.setBackground(new java.awt.Color(0, 255, 0));

        jLabel2.setText("Tahun");

        jLabel3.setText("Bulan");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jComboBox1, 0, 110, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));

        jLabel4.setText("Hasil");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        hitungJumlahHari.setText("Hitung");
        hitungJumlahHari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungJumlahHariActionPerformed(evt);
            }
        });

        hapusInput.setText("Hapus");
        hapusInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusInputActionPerformed(evt);
            }
        });

        simpanHasil.setText("Simpan");
        simpanHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanHasilActionPerformed(evt);
            }
        });

        keluarAplikasi.setText("Keluar");
        keluarAplikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarAplikasiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(hitungJumlahHari)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hapusInput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(simpanHasil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(keluarAplikasi)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hitungJumlahHari)
                    .addComponent(hapusInput)
                    .addComponent(simpanHasil)
                    .addComponent(keluarAplikasi))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Ketika tombol "Hitung" ditekan, metode ini akan dijalankan
    private void hitungJumlahHariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungJumlahHariActionPerformed
        // TODO add your handling code here:
        try {
            //Mendapatkan input tahun dari TextField dan mengubahnya menjadi tipe int
            int tahun = Integer.parseInt(jTextField1.getText());
            //Mendapatkan bulan yang dipilih dari JComboBox (index bulan dimulai dari 0, sehingga ditambahkan 1)
            int bulan = jComboBox1.getSelectedIndex() + 1; // Get month index (1-12)
            //Mendapatkan nama bulan yang dipilih dari JComboBox sebagai String
            String namaBulan = jComboBox1.getSelectedItem().toString();
            //Menghitung jumlah hari dengan memanggil metode hitung dari kelas hitungHari
            int jumlahHari = hitungHari.hitung(tahun, bulan);
            //Menampilkan hasil perhitungan pada jLabel4
            jLabel4.setText("Jumlah hari pada bulan " + namaBulan + " tahun " + tahun + " adalah " + jumlahHari);
        } catch (NumberFormatException e) {
            //Menampilkan pesan kesalahan jika input tahun bukan angka
            JOptionPane.showMessageDialog(this, "Input tahun harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_hitungJumlahHariActionPerformed

    private void hapusInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusInputActionPerformed
        // TODO add your handling code here:
        //Fungsi ini digunakan untuk menghapus input yang ada di TextField dan mengembalikan pilihan bulan ke default
        jTextField1.setText("");        //Menghapus isi TextField
        jComboBox1.setSelectedIndex(0); //Mengembalikan JComboBox ke pilihan bulan pertama (index 0)
        jLabel4.setText("Hasil");       //Mengatur ulang label hasil menjadi teks default
    }//GEN-LAST:event_hapusInputActionPerformed

    private void simpanHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanHasilActionPerformed
        // TODO add your handling code here:
        //Fungsi ini digunakan untuk menyimpan hasil perhitungan ke dalam file teks
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("hasil_perhitungan.txt"))) {
            //Menyimpan input tahun, bulan yang dipilih, dan hasil perhitungan ke dalam file teks
            writer.write("Tahun: " + jTextField1.getText());
            writer.write("\nBulan: " + jComboBox1.getSelectedItem().toString());
            writer.write("\n" + jLabel4.getText());
        
            //Menampilkan pesan bahwa hasil berhasil disimpan
             JOptionPane.showMessageDialog(this, "Hasil berhasil disimpan!", "Info", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException e) {
            //Menampilkan pesan kesalahan jika proses penyimpanan gagal
            JOptionPane.showMessageDialog(this, "Gagal menyimpan hasil!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_simpanHasilActionPerformed

    private void keluarAplikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarAplikasiActionPerformed
        // TODO add your handling code here:
        System.exit(0); //Menutup aplikasi
    }//GEN-LAST:event_keluarAplikasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenentuJumlahHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenentuJumlahHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenentuJumlahHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenentuJumlahHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenentuJumlahHari().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hapusInput;
    private javax.swing.JButton hitungJumlahHari;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton keluarAplikasi;
    private javax.swing.JButton simpanHasil;
    // End of variables declaration//GEN-END:variables
}
